stages:
  - build
  - publish

build:
  stage: build
  image: maven:3.8.8-eclipse-temurin-17
  script:
    - mvn clean verify -s $MAVEN_SETTINGS -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .m2/repository
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - when: never
  artifacts:
    paths:
      - ./**/target/*.jar

publish:
  stage: publish
  image: maven:3.8.8-eclipse-temurin-17
  script:
    - cat $MAVEN_SETTINGS
    - mvn deploy -s $MAVEN_SETTINGS -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .m2/repository
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/' # A specific tag with 'vX.Y.Z-release' pattern is created
    - when: never
#  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
#    tag_name: '$CI_COMMIT_TAG'
#    description: '$CI_COMMIT_TAG'
