package ee.cyber.cdoc2.server.scenarios;

/**
 * Test scenario identifiers, matching the ids used in the CDOC2 server test plan's
 */
public final class ScenarioIdentifiers {

    private ScenarioIdentifiers() {
    }

    public static final String POS_SID_AUTHENTICATE_01 = "POST_SID_AUTHENTICATE-POS-01";
    public static final String POS_SID_SESSION_01 = "GET_SID_SESSION-POS-01";
    public static final String POS_MID_AUTHENTICATE_01 = "POST_MID_AUTHENTICATE-POS-01";
    public static final String POS_MID_AUTHENTICATE_02 = "POST_MID_AUTHENTICATE-POS-02-DISPLAY_TEXT_FORMAT_DEFAULTING";
    public static final String POS_MID_SESSION_01 = "GET_MID_SESSION-POS-01";

    public static final String NEG_SID_AUTHENTICATE_01 = "POST_SID_AUTHENTICATE-NEG-01-SESSION_TOKEN_MISSING";
    public static final String NEG_SID_AUTHENTICATE_02 = "POST_SID_AUTHENTICATE-NEG-02-SESSION_TOKEN_MALFORMED";
    public static final String NEG_SID_AUTHENTICATE_03 = "POST_SID_AUTHENTICATE-NEG-03-SESSION_TOKEN_CERT_MISSING";
    public static final String NEG_SID_AUTHENTICATE_04 = "POST_SID_AUTHENTICATE-NEG-04-SESSION_TOKEN_CERT_MALFORMED";
    public static final String NEG_SID_AUTHENTICATE_05 =
        "POST_SID_AUTHENTICATE-NEG-05-SESSION_TOKEN_SUB_CERT_SN_MISMATCH";
    public static final String NEG_SID_AUTHENTICATE_06 = "POST_SID_AUTHENTICATE-NEG-06-REQUEST_BODY_MISSING";
    public static final String NEG_SID_AUTHENTICATE_07 = "POST_SID_AUTHENTICATE-NEG-07-SEMANTICS_IDENTIFIER_MISSING";
    public static final String NEG_SID_AUTHENTICATE_08 = "POST_SID_AUTHENTICATE-NEG-08-SIGNATURE_PROTOCOL_MISSING";
    public static final String NEG_SID_AUTHENTICATE_09 =
        "POST_SID_AUTHENTICATE-NEG-09-SIGNATURE_PROTOCOL_PARAMS_MISSING";
    public static final String NEG_SID_AUTHENTICATE_10 = "POST_SID_AUTHENTICATE-NEG-10-INTERACTIONS_MISSING";
    public static final String NEG_SID_AUTHENTICATE_11 = "POST_SID_AUTHENTICATE-NEG-11-VC_TYPE_MISSING";

    public static final String NEG_SID_SESSION_01 = "GET_SID_SESSION-NEG-01-SESSION_TOKEN_MISSING";
    public static final String NEG_SID_SESSION_02 = "GET_SID_SESSION-NEG-02-SESSION_TOKEN_MALFORMED";
    public static final String NEG_SID_SESSION_03 = "GET_SID_SESSION-NEG-03-SESSION_TOKEN_CERT_MISSING";
    public static final String NEG_SID_SESSION_04 = "GET_SID_SESSION-NEG-04-SESSION_TOKEN_CERT_MALFORMED";
    public static final String NEG_SID_SESSION_05 = "GET_SID_SESSION-NEG-05-SESSION_TOKEN_SUB_CERT_SN_MISMATCH";
    public static final String NEG_SID_SESSION_06 = "GET_SID_SESSION-NEG-06-SESSION_ID_MISSING";
    public static final String NEG_SID_SESSION_07 = "GET_SID_SESSION-NEG-07-SESSION_ID_MALFORMED";

    public static final String NEG_MID_AUTHENTICATE_01 = "POST_MID_AUTHENTICATE-NEG-01-SESSION_TOKEN_MISSING";
    public static final String NEG_MID_AUTHENTICATE_02 = "POST_MID_AUTHENTICATE-NEG-02-SESSION_TOKEN_MALFORMED";
    public static final String NEG_MID_AUTHENTICATE_03 =
        "POST_MID_AUTHENTICATE-NEG-03-SESSION_TOKEN_CERT_MISSING";
    public static final String NEG_MID_AUTHENTICATE_04 =
        "POST_MID_AUTHENTICATE-NEG-04-SESSION_TOKEN_CERT_MALFORMED";
    public static final String NEG_MID_AUTHENTICATE_05 =
        "POST_MID_AUTHENTICATE-NEG-05-SESSION_TOKEN_SUB_CERT_SN_MISMATCH";
    public static final String NEG_MID_AUTHENTICATE_06 = "POST_MID_AUTHENTICATE-NEG-06-REQUEST_BODY_MISSING";
    public static final String NEG_MID_AUTHENTICATE_07 = "POST_MID_AUTHENTICATE-NEG-07-PHONE_NUMBER_MISSING";
    public static final String NEG_MID_AUTHENTICATE_08 =
        "POST_MID_AUTHENTICATE-NEG-08-NATIONAL_IDENTIDY_NUMBER_MISSING";
    public static final String NEG_MID_AUTHENTICATE_09 = "POST_MID_AUTHENTICATE-NEG-09-HASH_MISSING";
    public static final String NEG_MID_AUTHENTICATE_10 =
        "POST_MID_AUTHENTICATE-NEG-10-HASH_TYPE_MISSING";
    public static final String NEG_MID_AUTHENTICATE_11 = "POST_MID_AUTHENTICATE-NEG-11-LANGUAGE_MISSING";
    public static final String NEG_MID_AUTHENTICATE_12 = "POST_MID_AUTHENTICATE-NEG-12-DISPLAY_TEXT_MISSING";

    public static final String NEG_MID_SESSION_01 = "GET_MID_SESSION-NEG-01-SESSION_TOKEN_MISSING";
    public static final String NEG_MID_SESSION_02 = "GET_MID_SESSION-NEG-02-SESSION_TOKEN_MALFORMED";
    public static final String NEG_MID_SESSION_03 = "GET_MID_SESSION-NEG-03-SESSION_TOKEN_CERT_MISSING";
    public static final String NEG_MID_SESSION_04 = "GET_MID_SESSION-NEG-04-SESSION_TOKEN_CERT_MALFORMED";
    public static final String NEG_MID_SESSION_05 = "GET_MID_SESSION-NEG-05-SESSION_TOKEN_SUB_CERT_SN_MISMATCH";
    public static final String NEG_MID_SESSION_06 = "GET_MID_SESSION-NEG-06-SESSION_ID_MISSING";
    public static final String NEG_MID_SESSION_07 = "GET_MID_SESSION-NEG-07-SESSION_ID_MALFORMED";
}
